import { FLAT_FILE_PLATFORMS } from "@/components/JobSpecExport";

function isFlat(platform) {
  return FLAT_FILE_PLATFORMS.includes(platform);
}

export function generateAirflowDAG(job, connections) {
  const sourceConn = connections.find(c => c.id === job.source_connection_id);
  const targetConn = connections.find(c => c.id === job.target_connection_id);
  const srcPlatform = sourceConn?.platform || "";
  const tgtPlatform = targetConn?.platform || "";

  const dagId = `dataflow__${(job.name || "pipeline").replace(/[^a-zA-Z0-9]/g, "_").toLowerCase()}`;
  const datasets = job.selected_datasets || job.selected_objects || [];

  const cronExpr = job.schedule_type === "manual" ? null
    : job.schedule_type === "hourly" ? "0 * * * *"
    : job.schedule_type === "daily" ? "0 0 * * *"
    : job.schedule_type === "weekly" ? "0 0 * * 0"
    : job.cron_expression || null;

  const scheduleStr = cronExpr ? `"${cronExpr}"` : "None";

  const taskDefs = datasets.map(ds => {
    const useFlat = isFlat(srcPlatform) || isFlat(tgtPlatform);
    const taskId = `${ds.schema}__${ds.table}`.replace(/[^a-zA-Z0-9_]/g, "_").toLowerCase();
    const loadMethod = ds.load_method || job.load_method || "append";

    if (useFlat) {
      return `
    # Task: ${ds.schema}.${ds.table} [PythonOperator - flat file]
    task_${taskId} = PythonOperator(
        task_id="${taskId}",
        python_callable=run_flat_file_ingestion,
        op_kwargs={
            "source_platform": "${srcPlatform}",
            "target_platform": "${tgtPlatform}",
            "schema": "${ds.schema}",
            "table": "${ds.table}",
            "target_path": "${ds.target_path || ""}",
            "load_method": "${loadMethod}",
            "filter_query": "${(ds.filter_query || "").replace(/"/g, '\\"')}",
            "incremental_column": "${ds.incremental_column || ""}",
        },
        retries=${job.retry_config?.max_retries ?? 3},
        retry_delay=timedelta(seconds=${job.retry_config?.retry_delay_seconds ?? 60}),
    )`;
    } else {
      return `
    # Task: ${ds.schema}.${ds.table} [SparkSubmitOperator - database/cloud]
    task_${taskId} = SparkSubmitOperator(
        task_id="${taskId}",
        application="dataflow_spark_ingestion.py",
        application_args=[
            "--schema", "${ds.schema}",
            "--table", "${ds.table}",
            "--target_path", "${ds.target_path || ""}",
            "--load_method", "${loadMethod}",
            "--filter_query", "${(ds.filter_query || "").replace(/"/g, '\\"')}",
            "--incremental_column", "${ds.incremental_column || ""}",
        ],
        conf={
            "spark.executor.memory": "4g",
            "spark.executor.cores": "2",
            "spark.driver.memory": "2g",
        },
        py_files=["dataflow_utils.zip"],
        retries=${job.retry_config?.max_retries ?? 3},
        retry_delay=timedelta(seconds=${job.retry_config?.retry_delay_seconds ?? 60}),
    )`;
    }
  });

  const taskIds = datasets.map(ds =>
    `task_${ds.schema}__${ds.table}`.replace(/[^a-zA-Z0-9_]/g, "_").toLowerCase()
  );

  const dependencyChain = taskIds.length > 1
    ? "\n    " + taskIds.join(" >> ") + "\n"
    : taskIds.length === 1 ? `\n    # Single task — no dependencies\n    ${taskIds[0]}\n` : "\n    pass\n";

  const usesFlat = isFlat(srcPlatform) || isFlat(tgtPlatform);
  const imports = usesFlat
    ? `from airflow.operators.python import PythonOperator`
    : `from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator`;

  return `# Auto-generated by DataFlow — ${new Date().toISOString()}
# Pipeline: ${job.name}
# Source: ${sourceConn?.name || job.source_connection_id} (${srcPlatform})
# Target: ${targetConn?.name || job.target_connection_id} (${tgtPlatform})

from datetime import datetime, timedelta
from airflow import DAG
${imports}

default_args = {
    "owner": "${job.assignment_group || "dataflow"}",
    "depends_on_past": False,
    "email_on_failure": ${job.email ? "True" : "False"},
    "email_on_retry": False,
    ${job.email ? `"email": ["${job.email}"],` : ""}
    "retries": ${job.retry_config?.max_retries ?? 3},
    "retry_delay": timedelta(seconds=${job.retry_config?.retry_delay_seconds ?? 60}),
}

with DAG(
    dag_id="${dagId}",
    default_args=default_args,
    description="${(job.description || "").replace(/"/g, '\\"')}",
    schedule_interval=${scheduleStr},
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["dataflow", "${usesFlat ? "flat_file" : "pyspark"}", "${job.schedule_type || "manual"}"],
) as dag:
${taskDefs.join("\n")}
${dependencyChain}`;
}